#!/usr/bin/env python3
"""Generate SQLite statement boundaries; --check never modifies the projection."""
import argparse
from pathlib import Path
import sqlite3

parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
base = root / 'crates/lenso-feature-flag-d1-plugin'
sql = (base / 'migrations/001_feature_flags.sql').read_text()
ends = []
start = 0
for end in range(1, len(sql) + 1):
    if sql[end - 1] == ';' and sqlite3.complete_statement(sql[start:end]):
        ends.append(len(sql[:end].encode()))
        start = end
assert not sql[start:].strip()
ends[-1] = len(sql.encode())
projection = '// Generated by scripts/generate-d1-migrations.py. Do not edit.\n&' + str(ends) + '\n'
target = base / 'src/migration_statement_ends.rs'
if args.check:
    assert target.read_text() == projection, 'stale D1 migration boundaries'
else:
    target.write_text(projection)
